### PR TITLE
LRA-413rs-art-survey-design-and-add-a-database

### PR DESCRIPTION
**Pull request by rsmoke**
This PR contains the code generated by using the Rails 'scaffold' generator to create the database models and associated files. I followed the databse diagram that @anantas and @brita worked on and brainstormed. This PR also include the install of ActinText which is a dependance on a few of the database fields.

I did not squash the comits to make the various items easier to read.

### CODE REVIEW

**Review by britaumich — COMMENTED** [review]
Some questions:

1. About Access and Permissions models. According to your schema, you don't need the uniqname field in the permissions table. According to my schema, you don't need the accesses table.
2. Should the archived field in the art_items table be boolean, not binary?
3. Why did you not install the annotate gem?

**Comment by rsmoke** [comment]
Good catch on the binary instead of the intended boolean column type for archived. i updated the PR code

**Comment by rsmoke** [comment]
Annotate won't work with Rails 7
```
 annotate (~> 2.7, >= 2.7.1) was resolved to 2.7.4, which depends on
      activerecord (< 6.0, >= 3.2)
```

**Comment by rsmoke** [comment]
I was following the schema that was showing the uniqname field even though in the diagram uniqname is hidden in the Permissions table. This has also been fixed

**Comment by britaumich** [comment]
'annotate', '~> 3.2' worked in my branch

> Annotate won't work with Rails 7
> 
> ```
>  annotate (~> 2.7, >= 2.7.1) was resolved to 2.7.4, which depends on
>       activerecord (< 6.0, >= 3.2)
> ```

**Comment by rsmoke** [comment]
> 'annotate', '~> 3.2' worked in my branch
> 
> > Annotate won't work with Rails 7
> > ```
> >  annotate (~> 2.7, >= 2.7.1) was resolved to 2.7.4, which depends on
> >       activerecord (< 6.0, >= 3.2)
> > ```

@britaumich I did not see annotate 3.2 when i searched for the gem. I added it and annotated the system, thanks

**Review by anantaUM — APPROVED** [review]

**Pull request merged**
