### PR TITLE
Lra 418 art survey design an individual item show page

### PR DESCRIPTION
**Pull request by britaumich**
This pull request has

- fix format for trix editor box
- new art_item page 
- show art_item page
- controller's methods to create and update an art_item including adding the current user to the updated_by field
- helper methods to display a date and current user
- partial to display a message that an item is archived in the show page

### CODE REVIEW

**Comment by britaumich** [comment]
@anantaUM I think all fields (even empty ones) should be displayed on the Show page. A user should know that those fields are empty.
To see archived items go to the Catalog and click the Archived checkbox in the filters area.

**Comment by anantaUM** [comment]
This somehow doesn't look so user friendly.
Screen Shot 2022-10-27 at 2 11 56 PM

Also, I would like to know Rick and Maria's opinion.

**Comment by britaumich** [comment]
@anantaUM I borrowed our styles from the VOD application. I would like to know Maria's opinion too. And Maria can look at the staging server and tell her opinion and create a new design. As well as Jessica or Linda. Right now I can only share my screen or create screenshots to show this design to Maria. It's not hard to change styles later. I think it's harder to evaluate something by looking only at screenshots or shared screens.

**Comment by anantaUM** [comment]
@britaumich - I will go ahead and approve this pull request. Please add this design question as an open item to discuss with Maria / Jessica / Linda. Thanks.

**Review by anantaUM — APPROVED** [review]

**Pull request merged**
