### PR TITLE
LRA-439-art-survey-home-logo

### PR DESCRIPTION
**Pull request by rsmoke**
Create a LSA logo and layout to replace the solitary Block M.

### CODE REVIEW

**Comment by britaumich** [comment]
I think the logo looks better without the white border.
Screen Shot 2022-11-03 at 3 53 13 PM
Screen Shot 2022-11-03 at 3 52 44 PM

**Comment by britaumich** [comment]
@rsmoke do you like this logo?
Screen Shot 2022-11-03 at 4 28 56 PM

**Comment by rsmoke** [comment]
I asked Maria for her opinion

**Comment by rsmoke** [comment]
Marai gave the eps for the M LSA white letter logo. I added it to the header and 'Admin' merged so she can see it on staging

**Pull request merged**
