### PR TITLE
LRA-424-art-survey-static-pages

### PR DESCRIPTION
**Pull request by rsmoke**
This PR removes the redundant 'privacy' page. It creates the ability to manage page information via scaffolded PageInformation. 

I removed the ability to add a new page as well as delete an existing page. This will make sure the record is persistent.

### CODE REVIEW

**Review by britaumich — CHANGES_REQUESTED** [review]
Please run annotate --models to add an annotation to the page_informations table.

Please add default data for the page_informations table (location) to the seed file.

**Comment by britaumich** [comment]
In static_pages_controller.rb please replace [**StaticPage**.find_by(location:...] with [**PageInformation**.find_by(location:...] on lines 4 and 8.

**Comment by rsmoke** [comment]
I wanted to capture this idea into a pull request and discuss

1. How to make it better
2. Capture it as a RailsPlaybook process that could be repeated

Please continue to review and think about it so we can discuss it.

**Comment by britaumich** [comment]
1. In the [Edit Page Information] there is a button [New page information] that redirects to the new page.
It should not exist, right?

2. On the index page [Edit Page Information] I would create links to edit page information for the About and Index pages.     Like in MClassrooms: https://mclassrooms-staging.lsa.umich.edu/announcements
        
3. There is some inconsistency in static page names and locations in the page_information table. See StaticPagesController: pages are called index and about; locations - home and about)

4. Static pages should have links to edit PageInformation.

**Review by britaumich — COMMENTED** [review]
in home.html.erb on line 3 the link should redirect to a page where you can edit the content of the home page_information (like we had it in VOD). Something like this:

<%= link_to "Edit Info", edit_page_information_path(@home_page_information), class: "#{class_names(active: current_page?(page_informations_path))}" %>

where @home_page_information = PageInformation.find_by(location: "home") if PageInformation.find_by(location: 'home').present?

**Comment by rsmoke** [comment]
> in home.html.erb on line 3 the link should redirect to a page where you can edit the content of the home page_information (like we had it in VOD). Something like this:
> 
> <%= link_to "Edit Info", edit_page_information_path(@home_page_information), class: "#{class_names(active: current_page?(page_informations_path))}" %>
> 
> where @home_page_information = PageInformation.find_by(location: "home") if PageInformation.find_by(location: 'home').present?

I want to go back to all page infos and not just the one.

**Comment by britaumich** [comment]
Ok, if you want. But then it would make sense to have a Page Information link which, we decided, we don't need. 
Again, I think you make it too complicated, but I know I would not win this argument.

**Review by britaumich — APPROVED** [review]
I approve it, but I don't agree with your design. 
You can merge it.

**Pull request merged**
