### PR TITLE
rebase staging into main

### PR DESCRIPTION
**Pull request by rsmoke**

### CODE REVIEW

**Comment by britaumich** [comment]
I don't understand why there are 8 commits in the PR but only the .gitignore file is changed.
Is that because the main was merged into staging? Twice? Why?
Could you please explain?

**Comment by rsmoke** [comment]
> I don't understand why there are 8 commits in the PR but only the .gitignore file is changed. Is that because the main was merged into staging? Twice? Why? Could you please explain?

Only Squash commits was enabled which preserves the history in the merging branch. I enabled 'rebase' a 'merge commits' so the history won't keep in the merging branch unless we specifically want it to.

**Comment by britaumich** [comment]
I'm sorry if I ask stupid questions, but I still don't understand. 
To "squash" in Git means to combine multiple commits into one. So, if commits were squashed, in the PR I expect to see fewer commits. And the files that were affected should be there. Here I see only the .gitignore file, but many commits.
Also, all commits except one (the .gitignore one) are 'verified'. And - it seems - that these commits are already in the main branch. 
What was the purpose of merging main into staging?

**Comment by rsmoke** [comment]
No stupid questions, git is a confusing beast sometimes m(Hence all the
history you are seeing)
Here is the various merge methods described
<https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github>.
I hope it helps

Basically we have been squashing and merging in ArtSurvey and MClassrooms
which uses the fast-forward options
<https://git-scm.com/docs/git-merge#_fast_forward_merge> causing the
confusing commit history.

Doing a basic merge commit or rebase
<https://git-scm.com/book/en/v2/Git-Branching-Rebasing> can fix this. I am
thinking we will fix it with a basic merge commit and all will be happy
again

**Review by britaumich — APPROVED** [review]

**Review by anantaUM — APPROVED** [review]

**Pull request merged**
