### PR TITLE
Lrs-429v2

### PR DESCRIPTION
**Pull request by rsmoke**
Dry up partial for page info text display. Update locations it is used on.

### CODE REVIEW

**Review by britaumich — COMMENTED** [review]
page_informations/index.html.erb should not have lines 2-4
```
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>
```

flash messages are displayed in the flash div by layouts/_flash.html.erb

**Comment by rsmoke** [comment]
> page_informations/index.html.erb should not have lines 2-4
> 
> ```
> <% if notice.present? %>
>   <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
> <% end %>
> ```
> 
> flash messages are displayed in the flash div by layouts/_flash.html.erb

The 'page_informations/index.html.erb'  page is not in this PR.

**Comment by britaumich** [comment]
But the PR's title says that it's version 2 of LRA-429 (https://umlsait.atlassian.net/jira/software/projects/LRA/boards/104?selectedIssue=LRA-429) which is about editing. From the PR description "...Update locations it is used on."
And updating your page (catalog) information gives two update messages.
- - - - - -
Screen Shot 2022-11-07 at 3 28 07 PM
----------

Do you want to create another ticket to remove the extra notice?

**Comment by britaumich** [comment]
Actually, it's not the index, but page_informations/show.html.erb that doesn't need to display a notice.
Or both of them.

**Comment by rsmoke** [comment]
I am merging this and then I will fix the multi notifications

**Pull request merged**
